# -*- coding: utf-8 -*-
import csv
import os
from pptx import Presentation
from pptx.util import Pt, Inches
from pypinyin import pinyin, Style
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

def create_mandarin_ppt(vocab_list, output_file):
    """
    Create a PowerPoint presentation with Mandarin vocabulary.

    Args:
        vocab_list (list of tuples): List of (Chinese, English) pairs.
        output_file (str): Path to save the PowerPoint file.
    """
    # Create a new PowerPoint presentation
    prs = Presentation()

    # Add a title slide
    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title = title_slide.shapes.title
    subtitle = title_slide.placeholders[1]
    title.text = "Mandarin Vocabulary"
    title.text_frame.paragraphs[0].font.size = Pt(60)
    title.text_frame.paragraphs[0].font.bold = True
    title.text_frame.paragraphs[0].font.color.rgb = RGBColor(255, 69, 0)  # Orange
    subtitle.text = "Generated by Mandarin PPT Generator"
    subtitle.text_frame.paragraphs[0].font.size = Pt(32)
    subtitle.text_frame.paragraphs[0].font.color.rgb = RGBColor(0, 128, 255)  # Blue

    # Add a slide for each vocabulary word
    for chinese, english in vocab_list:
        slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank slide layout

        # Set background color
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(255, 239, 213)  # Light peach

        # Add pinyin at the top right
        pinyin_text = ' '.join([p[0] for p in pinyin(chinese, style=Style.TONE)])
        pinyin_box = slide.shapes.add_textbox(Inches(6), Inches(0.5), Inches(3), Inches(1))
        pinyin_frame = pinyin_box.text_frame
        pinyin_frame.text = pinyin_text
        pinyin_frame.paragraphs[0].font.size = Pt(28)
        pinyin_frame.paragraphs[0].font.color.rgb = RGBColor(0, 100, 0)  # Dark green
        pinyin_frame.paragraphs[0].alignment = PP_ALIGN.RIGHT

        # Add Chinese character in the middle right
        chinese_box = slide.shapes.add_textbox(Inches(6), Inches(2), Inches(3), Inches(2))
        chinese_frame = chinese_box.text_frame
        chinese_frame.text = chinese
        chinese_frame.paragraphs[0].font.size = Pt(60)
        chinese_frame.paragraphs[0].font.bold = True
        chinese_frame.paragraphs[0].font.color.rgb = RGBColor(255, 0, 0)  # Red
        chinese_frame.paragraphs[0].alignment = PP_ALIGN.RIGHT

        # Add English at the bottom right
        english_box = slide.shapes.add_textbox(Inches(6), Inches(4.5), Inches(3), Inches(1))
        english_frame = english_box.text_frame
        english_frame.text = english
        english_frame.paragraphs[0].font.size = Pt(28)
        english_frame.paragraphs[0].font.color.rgb = RGBColor(0, 0, 255)  # Blue
        english_frame.paragraphs[0].alignment = PP_ALIGN.RIGHT

    # Save the presentation
    prs.save(output_file)
    print(f"Presentation saved to {output_file}")

if __name__ == "__main__":
    vocab = []
    input_method = input("Enter '1' to load vocabulary from a CSV file or '2' to input manually: ").strip()

    if input_method == '1':
        csv_file = input("Enter the path to the CSV file (default: vocab.csv): ").strip()
        if not csv_file:
            csv_file = "vocab.csv"

        try:
            with open(csv_file, mode="r", encoding="utf-8") as file:
                reader = csv.reader(file)
                for row in reader:
                    if len(row) >= 2:
                        chinese, english = row[0].strip(), row[1].strip()
                        vocab.append((chinese, english))
        except FileNotFoundError:
            print(f"Error: File '{csv_file}' not found. Exiting.")
            exit(1)
    elif input_method == '2':
        print("Paste vocabulary pairs in the format 'Chinese, English', one pair per line.")
        print("Type 'done' on a new line when you are finished.")
        bulk_input = []
        while True:
            line = input().strip()
            if line.lower() == 'done':
                break
            bulk_input.append(line)

        for line in bulk_input:
            if ',' in line:
                chinese, english = map(str.strip, line.split(',', 1))
                vocab.append((chinese, english))
            else:
                print(f"Skipping invalid line: {line}. Please use 'Chinese, English' format.")
    else:
        print("Invalid option. Exiting.")
        exit(1)

    if not vocab:
        print("No vocabulary provided. Exiting.")
    else:
        output_path = input("Enter output file path (default: Mandarin_Vocabulary_PPT.pptx): ").strip()
        if not output_path:
            output_path = "Mandarin_Vocabulary_PPT.pptx"
        elif not output_path.lower().endswith(".pptx"):
            output_path += ".pptx"
        create_mandarin_ppt(vocab, output_path)